### ISSUE TITLE
Lage en klar plan for de 20 min, med tanke på oppsett rundt

### ISSUE THREAD

**Issue by cornelia771** [Burhan-Mohammad-Sarfraz/deckdazzle#14]

**Comment by williams-ye-bouvet** [comment]
https://bouvetasa-my.sharepoint.com/:w:/g/personal/william_ye_bouvet_no/EQreB_Bg1F1FtBqLURRIEMUBt6nh7Wd7X1wq-FxTf-0A_Q

Midlertidig dokument
